### ISSUE TITLE
error after build app and its crashing

### ISSUE THREAD

**Issue by itsDantes** [SaeedDev94/Xray#10]
app crashing on **hev-socks5-tunnel** version.

![Untitled](https://github.com/SaeedDev94/Xray/assets/37669470/2280561a-87ad-4094-b841-8afccd0fc75c)

`
FATAL EXCEPTION: main
                                                                                                    Process: com.xtls.xray, PID: 6501
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libhev-socks5-tunnel.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at com.xtls.xray.TProxyService.<clinit>(TProxyService.kt:20)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:74)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4330)
                                                                                                    	at android.app.ActivityThread.access$1800(ActivityThread.java:263)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8057)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
`

where is **libhev-socks5-tunnel.so** files ??? it not creating in jniLibs folder. i never changed anything. just downloaded this project as raw into my android studio and getting this error.

**Comment by itsDantes** [comment]
is there any way to not use of **externalNativeBuild** and just put .so files in lib folder and run them via command line?

**Comment by SaeedDev94** [comment]
First you need to clone the project with `--recursive` option
Second you have to install the specific version of nkd that i set in `externalNativeBuild`  
From `v1.7.0` and above `heiher/hev-socks5-tunnel` is the new tun2socks tool for this project

**Comment by itsDantes** [comment]
@SaeedDev94  well. when i  use **--recursive** command i getting below error.
`
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts. git@github.com: Permission denied (publickey). Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists. clone of 'git@github.com:heiher/hev-socks5-tunnel.git' into submodule path 'C:/Users/windows/StudioProjects/Xray/app/src/main/jni/hev-socks5-tunnel' failed Failed to clone 'app/src/main/jni/hev-socks5-tunnel'. Retry scheduled git@github.com: Permission denied (publickey). Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists. clone of 'git@github.com:heiher/hev-socks5-tunnel.git' into submodule path 'C:/Users/windows/StudioProjects/Xray/app/src/main/jni/hev-socks5-tunnel' failed Failed to clone 'app/src/main/jni/hev-socks5-tunnel' a second time, aborting
`

**Comment by SaeedDev94** [comment]
You should fix your setup (ssh key)

**Comment by itsDantes** [comment]
It got complicated. when i clone your git via android studio directly i getting this error while another gits are okay. the only way is just downlaod this project via github zip file and unzip in system, then import it to android studio and by that way i getting **dlopen failed: library "libhev-socks5-tunnel.so" not found** error. it would be nice if you put .so files directly in lib folder.
i also opened [**an issuse**](https://github.com/heiher/hev-socks5-tunnel/issues/94) in and them them about building problem.

**Comment by SaeedDev94** [comment]
The build process is straightforward, also I'm not sure if it's possible to create a `lib.so` for `heiher/hev-socks5-tunnel` and use its native methods inside the VpnService  
Even if it is possible to do that I'm not willing to do it because I have to build it for different platforms (ABI) and the app size will increase
